// src/lib/llm.ts
// Optional LLM-powered plan generation (Groq or OpenAI — OpenAI-compatible APIs)

import type { DocumentBundle, PlanStep } from '@/types'
import type { GeneratePlanInput, GeneratedPlan } from '@/lib/plan-engine'
import { generateMvpPlan } from '@/lib/plan-engine'

const GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions'
const OPENAI_URL = 'https://api.openai.com/v1/chat/completions'

export type LlmProvider = 'groq' | 'openai' | 'none'

function resolveLlmConfig(): {
  provider: LlmProvider
  apiKey: string
  baseUrl: string
  model: string
} | null {
  const explicit = process.env.LLM_PROVIDER?.toLowerCase()

  if (process.env.GROQ_API_KEY && explicit !== 'openai') {
    return {
      provider: 'groq',
      apiKey: process.env.GROQ_API_KEY,
      baseUrl: GROQ_URL,
      model: process.env.GROQ_MODEL || 'llama-3.3-70b-versatile',
    }
  }

  if (process.env.OPENAI_API_KEY && explicit !== 'groq') {
    return {
      provider: 'openai',
      apiKey: process.env.OPENAI_API_KEY,
      baseUrl: OPENAI_URL,
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
    }
  }

  return null
}

export function isLlmEnabled(): boolean {
  return resolveLlmConfig() !== null
}

export function getLlmProvider(): LlmProvider {
  return resolveLlmConfig()?.provider ?? 'none'
}

interface LlmPlanResponse {
  steps: {
    order: number
    title: string
    goal: string
    constraints: string[]
    expectedFiles: string[]
    verification: string[]
  }[]
  documents: {
    prd: string
    trd: string
    useCases: string
    testPlan: string
    architecture: string
    erd?: string
  }
}

export async function generatePlanWithLlm(input: GeneratePlanInput): Promise<GeneratedPlan> {
  const config = resolveLlmConfig()
  if (!config) {
    return { ...generateMvpPlan(input), source: 'rules' }
  }

  try {
    const res = await fetch(config.baseUrl, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: config.model,
        response_format: { type: 'json_object' },
        messages: [
          {
            role: 'system',
            content: `You are an MVP planning assistant. Return JSON with "steps" (array of 4-8 steps) and "documents" (prd, trd, useCases, testPlan, architecture as markdown strings). Each step needs: order, title, goal, constraints[], expectedFiles[], verification[]. Keep MVP scope minimal.`,
          },
          {
            role: 'user',
            content: `Plan an MVP for:\nTitle: ${input.title}\nRepo: ${input.repo}\nPrompt: ${input.originalPrompt}`,
          },
        ],
        temperature: 0.3,
      }),
    })

    if (!res.ok) {
      console.error(`[llm] ${config.provider} error`, res.status, await res.text())
      return { ...generateMvpPlan(input), source: 'rules' }
    }

    const data = (await res.json()) as {
      choices?: { message?: { content?: string } }[]
    }
    const content = data.choices?.[0]?.message?.content
    if (!content) return { ...generateMvpPlan(input), source: 'rules' }

    const parsed = JSON.parse(content) as LlmPlanResponse
    const branchPrefix = `ops/${input.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}`

    const steps: PlanStep[] = parsed.steps.map((s) => ({
      order: s.order,
      title: s.title,
      goal: s.goal,
      constraints: s.constraints?.length
        ? s.constraints
        : [`Branch: ${branchPrefix}-<timestamp>`, 'Write audit JSON when done'],
      expectedFiles: s.expectedFiles ?? [],
      verification: s.verification ?? ['lint clean'],
      status: 'pending' as const,
      agentPrompt: buildStepPromptFromLlm(s, input),
    }))

    const documents: DocumentBundle = {
      prd: parsed.documents?.prd || '# PRD\n(generated by LLM)',
      trd: parsed.documents?.trd || '# TRD\n(generated by LLM)',
      useCases: parsed.documents?.useCases || '# Use Cases',
      testPlan: parsed.documents?.testPlan || '# Test Plan',
      architecture: parsed.documents?.architecture || '# Architecture',
      erd: parsed.documents?.erd || '# ERD\n(generated by LLM)',
    }

    return { steps, documents, source: 'llm' }
  } catch (err) {
    console.error('[llm] Failed, falling back to rules:', err)
    return { ...generateMvpPlan(input), source: 'rules' }
  }
}

function buildStepPromptFromLlm(
  step: LlmPlanResponse['steps'][0],
  ctx: GeneratePlanInput,
): string {
  return `TASK: ${step.title}
GOAL: ${step.goal}
CONSTRAINTS:
${(step.constraints ?? []).map((c) => `  - ${c}`).join('\n')}
CONTEXT:
  - Repo: ${ctx.repo}
  - MVP: ${ctx.originalPrompt.slice(0, 300)}
AUDIT: Write .ops/runs/<run_id>/last_run.json per .opstwin/rules.md
`
}
